
DROP DATABASE IF EXISTS evolve_ai;

CREATE DATABASE evolve_ai;

CREATE TABLE "user" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(25) NOT NULL,
    email VARCHAR(100) UNIQUE,
    password TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE skill (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY  KEY,
    name VARCHAR(25) UNIQUE,
    category VARCHAR(30) NOT NULL
);

CREATE TABLE opportunity (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(25),
    description TEXT,
    estimated_income DECIMAL(10,2),
    link VARCHAR(255),
    created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE opportunity_skill (
    opportunity_id INT,
    skill_id INT,
    FOREIGN KEY (opportunity_id) REFERENCES opportunity(id),
    FOREIGN KEY (skill_id) REFERENCES skill(id),
    PRIMARY KEY (skill_id,opportunity_id)
);

CREATE TYPE learn_style AS ENUM ('visual','text','project');
CREATE TYPE device_type AS ENUM ('phone','laptop','desktop');
CREATE TYPE task_proof_status AS ENUM ('pending','approved','rejected');
CREATE TYPE task_status AS ENUM ('pending','completed');

CREATE TABLE "profile" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    age INT,
    income_goal TEXT,
    time_available VARCHAR(30),
    current_stat TEXT,
    device device_type,
    learning_style learn_style
);

CREATE TABLE post (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    content TEXT,
    created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE "like" (
    user_id INT,
    post_id INT,
    FOREIGN KEY (user_id) REFERENCES "user"(id),
    FOREIGN KEY (post_id) REFERENCES post(id),
    PRIMARY KEY (user_id,post_id)
);

CREATE TABLE daily_plan (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    plan_date DATE DEFAULT (CURRENT_DATE),
    goal_summary TEXT,
    completion_rate int,
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE task (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id INT,
    title TEXT,
    description TEXT,
    duration TEXT,
    priority TEXT,
    status task_status DEFAULT 'pending',
    is_skill_validation BOOLEAN
);

CREATE TABLE user_skill (
    user_id INT,
    skill_id INT,
    level INT,
    is_verified BOOLEAN,
    FOREIGN KEY (user_id) REFERENCES "user"(id),
    FOREIGN KEY (skill_id) REFERENCES skill(id)
);

CREATE TABLE task_proof (
    id iNT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id INT,
    user_inputs JSON,
    ai_feedback JSON,
    status task_proof_status);

CREATE TABLE password_reset (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    token VARCHAR(255) NOT NULL,
    expired_at TIMESTAMP
);
